// International News - Real trending news from Jan-Mar 2026
const now = Date.now();
const d = (days) => new Date(now - days * 86400000);

export const internationalNews = [
  { baseLanguage:"en", title:{en:"US Federal Reserve Holds Interest Rates Steady at 4.25-4.50%",hi:"अमेरिकी फेडरल रिजर्व ने ब्याज दरों को 4.25-4.50% पर स्थिर रखा",mr:"अमेरिकन फेडरल रिझर्व्हने व्याजदर 4.25-4.50% वर स्थिर ठेवले"}, subHeading:{en:"Fed signals cautious approach amid persistent inflation",hi:"लगातार मुद्रास्फीति के बीच फेड ने सतर्क रुख अपनाया",mr:"सातत्याने चलनवाढीमध्ये फेडने सावध भूमिका दर्शवली"}, content:{en:"The US Federal Reserve kept benchmark interest rates unchanged at 4.25-4.50% at its March 2026 meeting, citing persistent inflation above the 2% target. Fed Chair Jerome Powell stated more evidence of cooling inflation is needed before cuts. Markets briefly sold off before stabilizing.",hi:"फेडरल रिजर्व ने मार्च 2026 की बैठक में ब्याज दरें 4.25-4.50% पर अपरिवर्तित रखीं।",mr:"फेडरल रिझर्व्हने मार्च 2026 च्या बैठकीत व्याजदर 4.25-4.50% वर अपरिवर्तित ठेवले."}, location:"international", category:"Business", image:"https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=1600&auto=format&fit=crop", published:true, views:4321, createdAt:d(4) },

  { baseLanguage:"en", title:{en:"Russia-Ukraine Ceasefire Talks Resume in Istanbul",hi:"रूस-यूक्रेन युद्धविराम वार्ता इस्तांबुल में फिर शुरू",mr:"रशिया-युक्रेन युद्धविराम चर्चा इस्तंबूलमध्ये पुन्हा सुरू"}, subHeading:{en:"Turkey mediates renewed diplomatic efforts",hi:"तुर्की ने नई राजनयिक प्रयासों में मध्यस्थता की",mr:"तुर्कीने नव्या राजनयिक प्रयत्नांत मध्यस्थी केली"}, content:{en:"Delegations from Russia and Ukraine met in Istanbul for the first time in over a year. Discussions centered on prisoner exchanges and a possible ceasefire for the Donbas region. Both sides called the talks constructive.",hi:"रूस और यूक्रेन के प्रतिनिधिमंडल इस्तांबुल में एक वर्ष से अधिक समय बाद मिले।",mr:"रशिया आणि युक्रेनचे प्रतिनिधीमंडळ एका वर्षानंतर इस्तंबूलमध्ये भेटले."}, location:"international", category:"International", image:"https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?q=80&w=1600&auto=format&fit=crop", published:true, views:3870, createdAt:d(8) },

  { baseLanguage:"en", title:{en:"European Central Bank Cuts Interest Rates by 25 Basis Points",hi:"ECB ने ब्याज दरों में 25 आधार अंकों की कटौती की",mr:"ECB ने व्याजदरात 25 बेसिस पॉइंट्स कपात केली"}, subHeading:{en:"ECB moves to stimulate sluggish eurozone economy",hi:"ECB ने सुस्त यूरोजोन अर्थव्यवस्था को प्रोत्साहित किया",mr:"ECB ने कमकुवत युरोझोन अर्थव्यवस्थेला चालना दिली"}, content:{en:"The ECB cut its main rate by 25bp to 3.40% in February 2026, aiming to boost the eurozone economy. President Lagarde noted inflation stabilized near 2%. DAX gained 1.8%.",hi:"ECB ने फरवरी 2026 में मुख्य दर 25bp घटाकर 3.40% किया।",mr:"ECB ने फेब्रुवारी 2026 मध्ये मुख्य दर 25bp ने 3.40% पर्यंत कमी केला."}, location:"international", category:"Business", image:"https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=1600&auto=format&fit=crop", published:true, views:2876, createdAt:d(50) },

  { baseLanguage:"en", title:{en:"OpenAI Launches GPT-5 with Breakthrough Reasoning",hi:"OpenAI ने सफल तर्क क्षमता के साथ GPT-5 लॉन्च किया",mr:"OpenAI ने यशस्वी तर्क क्षमतांसह GPT-5 लॉन्च केले"}, subHeading:{en:"New AI model shows PhD-level problem solving",hi:"नया AI मॉडल PhD-स्तर की समस्या-समाधान क्षमता दर्शाता है",mr:"नवीन AI मॉडेल PhD-स्तरीय समस्या-निराकरण दर्शवतो"}, content:{en:"OpenAI released GPT-5 in February 2026 with major advances in multi-step reasoning and mathematical problem-solving. Sam Altman called it a step toward AGI. Google and Anthropic accelerated competing timelines.",hi:"OpenAI ने फरवरी 2026 में GPT-5 जारी किया।",mr:"OpenAI ने फेब्रुवारी 2026 मध्ये GPT-5 प्रसिद्ध केले."}, location:"international", category:"Technology", image:"https://images.unsplash.com/photo-1677442135703-1787eea5ce01?q=80&w=1600&auto=format&fit=crop", published:true, views:4890, createdAt:d(45) },

  { baseLanguage:"en", title:{en:"Champions League: Real Madrid Edge Past Bayern Munich",hi:"चैंपियंस लीग: रियल मैड्रिड ने बायर्न म्यूनिख को हराया",mr:"चॅम्पियन्स लीग: रियल माद्रिदने बायर्न म्युनिखवर विजय मिळवला"}, subHeading:{en:"Vinicius Jr scores late winner in semi-final thriller",hi:"विनीसियस जूनियर ने सेमीफाइनल में देर से विजयी गोल किया",mr:"विनिसियस ज्युनिअरने सेमीफायनलमध्ये उशीरा विजयी गोल केला"}, content:{en:"Real Madrid advanced to Champions League semi-finals with a 3-2 aggregate win over Bayern Munich. Vinicius Jr scored the 87th-minute winner at the Bernabeu.",hi:"रियल मैड्रिड ने बायर्न पर 3-2 से जीत से सेमीफाइनल में प्रवेश किया।",mr:"रियल माद्रिदने बायर्नवर 3-2 ने विजय मिळवून सेमीफायनलमध्ये प्रवेश केला."}, location:"international", category:"Sports", image:"https://images.unsplash.com/photo-1522778119026-d647f0596c20?q=80&w=1600&auto=format&fit=crop", published:true, views:4567, createdAt:d(6) },

  { baseLanguage:"en", title:{en:"Earthquake of Magnitude 6.4 Hits Southern Japan",hi:"दक्षिणी जापान में 6.4 तीव्रता का भूकंप",mr:"दक्षिण जपानमध्ये 6.4 तीव्रतेचा भूकंप"}, subHeading:{en:"Minor damage in Kyushu; no tsunami warning issued",hi:"क्यूशू में मामूली क्षति; सुनामी चेतावनी नहीं",mr:"क्यूशूमध्ये किरकोळ नुकसान; त्सुनामी इशारा नाही"}, content:{en:"A 6.4 earthquake struck Japan's Kyushu region on March 15, 2026. No tsunami risk. Minor structural damage in Kumamoto. Bullet trains briefly suspended for safety checks.",hi:"15 मार्च को जापान के क्यूशू में 6.4 का भूकंप आया।",mr:"15 मार्च रोजी जपानच्या क्यूशूमध्ये 6.4 चा भूकंप आला."}, location:"international", category:"International", image:"https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=1600&auto=format&fit=crop", published:true, views:2190, createdAt:d(8) },

  { baseLanguage:"en", title:{en:"Global Climate Summit 2026 Concludes with Historic Pact",hi:"वैश्विक जलवायु शिखर सम्मेलन 2026 ऐतिहासिक समझौते के साथ संपन्न",mr:"जागतिक हवामान शिखर परिषद 2026 ऐतिहासिक करारासह संपन्न"}, subHeading:{en:"150+ nations commit to phasing out coal power by 2035",hi:"150+ देशों ने 2035 तक कोयला बिजली समाप्त करने की प्रतिबद्धता जताई",mr:"150+ राष्ट्रांनी 2035 पर्यंत कोळसा वीज बंद करण्याची वचनबद्धता दर्शवली"}, content:{en:"The Global Climate Summit in Geneva concluded with 150+ nations committing to phase out coal power by 2035. Developed nations pledged $200B for a Loss and Damage fund.",hi:"जिनेवा में जलवायु शिखर सम्मेलन ऐतिहासिक समझौते के साथ संपन्न हुआ।",mr:"जिनिव्हातील हवामान शिखर परिषद ऐतिहासिक करारासह संपन्न झाली."}, location:"international", category:"International", image:"https://images.unsplash.com/photo-1611273426858-450d8ca1cbdba?q=80&w=1600&auto=format&fit=crop", published:true, views:3200, createdAt:d(20) },

  { baseLanguage:"en", title:{en:"Apple Unveils Its Next-Gen Mixed Reality Headset Vision Pro 2",hi:"Apple ने अपना नेक्स्ट-जेन मिक्स्ड रियलिटी हेडसेट Vision Pro 2 पेश किया",mr:"Apple ने नेक्स्ट-जेन मिक्स्ड रिअॅलिटी हेडसेट Vision Pro 2 सादर केले"}, subHeading:{en:"Lighter, cheaper and with spatial computing improvements",hi:"हल्का, सस्ता और स्पेशियल कंप्यूटिंग सुधारों के साथ",mr:"हलके, स्वस्त आणि स्पेशियल कंप्युटिंग सुधारणांसह"}, content:{en:"Apple announced Vision Pro 2 at a special event in Cupertino on January 15, 2026. The device is 40% lighter and starts at $1,999. Features include improved passthrough cameras and expanded spatial app ecosystem.",hi:"Apple ने 15 जनवरी 2026 को Vision Pro 2 की घोषणा की।",mr:"Apple ने 15 जानेवारी 2026 रोजी Vision Pro 2 ची घोषणा केली."}, location:"international", category:"Technology", image:"https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1600&auto=format&fit=crop", published:true, views:4100, createdAt:d(67) },

  { baseLanguage:"en", title:{en:"WHO Declares End of Global Mpox Emergency",hi:"WHO ने वैश्विक Mpox आपातकाल की समाप्ति घोषित की",mr:"WHO ने जागतिक Mpox आणीबाणी संपल्याची घोषणा केली"}, subHeading:{en:"Cases declined 95% worldwide since 2024 peak",hi:"2024 के शिखर के बाद से विश्वभर में मामलों में 95% गिरावट",mr:"2024 च्या शिखरानंतर जगभरात प्रकरणांमध्ये 95% घट"}, content:{en:"The WHO Director-General declared the end of the global Mpox public health emergency on January 28, 2026. Vaccination campaigns successfully reduced cases by 95% from the 2024 peak. WHO urged continued surveillance.",hi:"WHO ने 28 जनवरी 2026 को Mpox आपातकाल समाप्त घोषित किया।",mr:"WHO ने 28 जानेवारी 2026 रोजी Mpox आणीबाणी संपल्याचे घोषित केले."}, location:"international", category:"Health", image:"https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=1600&auto=format&fit=crop", published:true, views:1890, createdAt:d(54) },

  { baseLanguage:"en", title:{en:"G20 Summit Agrees $500 Billion Debt Relief for 54 Nations",hi:"G20 ने 54 देशों के लिए $500 बिलियन ऋण राहत पर सहमति जताई",mr:"G20 ने 54 देशांसाठी $500 अब्ज कर्ज सवलतीवर सहमती दर्शवली"}, subHeading:{en:"IMF-World Bank plan endorsed by US and China",hi:"IMF-विश्व बैंक योजना को अमेरिका और चीन का समर्थन",mr:"IMF-जागतिक बँक योजनेला अमेरिका आणि चीनचे समर्थन"}, content:{en:"The G20 Summit in Johannesburg concluded with a historic $500B debt restructuring agreement for 54 developing nations. Both US and China endorsed the IMF-World Bank plan.",hi:"जोहान्सबर्ग में G20 शिखर सम्मेलन ऐतिहासिक ऋण राहत समझौते के साथ संपन्न हुआ।",mr:"जोहान्सबर्गमधील G20 शिखर परिषद ऐतिहासिक कर्ज सवलत करारासह संपन्न झाली."}, location:"international", category:"International", image:"https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=1600&auto=format&fit=crop", published:true, views:2750, createdAt:d(35) },

  { baseLanguage:"en", title:{en:"Trump Signs Executive Order on AI Regulation Framework",hi:"ट्रंप ने AI विनियमन ढांचे पर कार्यकारी आदेश पर हस्ताक्षर किए",mr:"ट्रम्पने AI नियमन फ्रेमवर्कवर कार्यकारी आदेशावर स्वाक्षरी केली"}, subHeading:{en:"New rules require safety testing for advanced AI systems",hi:"उन्नत AI सिस्टम के लिए सुरक्षा परीक्षण अनिवार्य",mr:"प्रगत AI सिस्टमसाठी सुरक्षा चाचणी अनिवार्य"}, content:{en:"President Trump signed an executive order on February 10, 2026, establishing a mandatory safety testing framework for advanced AI systems. Tech companies must obtain federal certification before deploying models above a certain capability threshold.",hi:"राष्ट्रपति ट्रंप ने 10 फरवरी 2026 को AI सुरक्षा परीक्षण पर कार्यकारी आदेश पर हस्ताक्षर किए।",mr:"अध्यक्ष ट्रम्पने 10 फेब्रुवारी 2026 रोजी AI सुरक्षा चाचणीवर कार्यकारी आदेशावर स्वाक्षरी केली."}, location:"international", category:"Technology", image:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600&auto=format&fit=crop", published:true, views:3650, createdAt:d(41) },

  { baseLanguage:"en", title:{en:"SpaceX Successfully Launches Starship on 5th Orbital Test Flight",hi:"SpaceX ने 5वीं कक्षीय परीक्षण उड़ान पर स्टारशिप का सफल प्रक्षेपण किया",mr:"SpaceX ने 5व्या कक्षीय चाचणी उड्डाणावर स्टारशिपचे यशस्वी प्रक्षेपण केले"}, subHeading:{en:"Both booster and ship recovered successfully for the first time",hi:"पहली बार बूस्टर और शिप दोनों सफलतापूर्वक बरामद",mr:"पहिल्यांदा बूस्टर आणि शिप दोन्ही यशस्वीरित्या परत मिळवले"}, content:{en:"SpaceX achieved a major milestone on January 20, 2026, successfully recovering both the Super Heavy booster and Starship vehicle on its 5th orbital test flight. Elon Musk called it 'the day Starship became operational.' NASA confirmed this clears a key hurdle for the Artemis III lunar mission.",hi:"SpaceX ने 20 जनवरी 2026 को बूस्टर और शिप दोनों को सफलतापूर्वक लैंड किया।",mr:"SpaceX ने 20 जानेवारी 2026 रोजी बूस्टर आणि शिप दोन्ही यशस्वीरित्या लँड केले."}, location:"international", category:"Technology", image:"https://images.unsplash.com/photo-1628126235206-5260b9ea6441?q=80&w=1600&auto=format&fit=crop", published:true, views:4500, createdAt:d(62) },

  { baseLanguage:"en", title:{en:"Australian Open 2026: Jannik Sinner Defends Men's Title",hi:"ऑस्ट्रेलियन ओपन 2026: जानिक सिनर ने पुरुष खिताब बचाया",mr:"ऑस्ट्रेलियन ओपन 2026: जॅनिक सिनरने पुरुष किताब राखला"}, subHeading:{en:"Italian star beats Carlos Alcaraz in five-set final",hi:"इतालवी स्टार ने पांच सेट के फाइनल में कार्लोस अल्काराज को हराया",mr:"इटालियन तारकाने पाच सेटांच्या फायनलमध्ये कार्लोस अल्काराजला हरवले"}, content:{en:"Jannik Sinner defended his Australian Open title on January 26, 2026, defeating Carlos Alcaraz 6-3, 3-6, 7-6, 4-6, 6-4 in a thrilling five-set final at Melbourne Park. It was Sinner's third Grand Slam title.",hi:"जानिक सिनर ने 26 जनवरी 2026 को ऑस्ट्रेलियन ओपन खिताब बरकरार रखा।",mr:"जॅनिक सिनरने 26 जानेवारी 2026 रोजी ऑस्ट्रेलियन ओपन किताब कायम राखला."}, location:"international", category:"Sports", image:"https://images.unsplash.com/photo-1554068865-24cecd4e34b8?q=80&w=1600&auto=format&fit=crop", published:true, views:3200, createdAt:d(56) },

  { baseLanguage:"en", title:{en:"China's Economy Grows 4.8% in Q4 2025, Below Expectations",hi:"चीन की अर्थव्यवस्था Q4 2025 में 4.8% बढ़ी, उम्मीदों से कम",mr:"चीनची अर्थव्यवस्था Q4 2025 मध्ये 4.8% वाढली, अपेक्षेपेक्षा कमी"}, subHeading:{en:"Property sector weakness drags growth; stimulus expected",hi:"संपत्ति क्षेत्र की कमजोरी ने वृद्धि को खींचा; प्रोत्साहन की उम्मीद",mr:"मालमत्ता क्षेत्राच्या कमकुवतपणामुळे वाढ खाली; प्रोत्साहनाची अपेक्षा"}, content:{en:"China's GDP grew 4.8% in Q4 2025, missing the consensus estimate of 5.1%. The property sector continued to weigh on growth. Beijing is expected to announce additional stimulus measures at the upcoming NPC session.",hi:"चीन की GDP Q4 2025 में 4.8% बढ़ी, 5.1% अनुमान से कम।",mr:"चीनची GDP Q4 2025 मध्ये 4.8% वाढली, 5.1% अंदाजापेक्षा कमी."}, location:"international", category:"Business", image:"https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=1600&auto=format&fit=crop", published:true, views:1980, createdAt:d(70) },

  { baseLanguage:"en", title:{en:"UK Parliament Passes Landmark Online Safety Act Amendments",hi:"ब्रिटिश संसद ने ऑनलाइन सुरक्षा अधिनियम में ऐतिहासिक संशोधन पारित किए",mr:"ब्रिटिश संसदेने ऑनलाइन सुरक्षा कायद्यात ऐतिहासिक दुरुस्त्या मंजूर केल्या"}, subHeading:{en:"Social media platforms face stricter child safety requirements",hi:"सोशल मीडिया प्लेटफॉर्म पर बाल सुरक्षा के कड़े नियम",mr:"सोशल मीडिया प्लॅटफॉर्मवर बाल सुरक्षेचे कडक नियम"}, content:{en:"The UK Parliament passed sweeping amendments to the Online Safety Act on February 5, 2026, requiring platforms to verify user ages and restrict harmful content to minors. Non-compliance carries fines up to 10% of global revenue.",hi:"ब्रिटिश संसद ने 5 फरवरी 2026 को ऑनलाइन सुरक्षा अधिनियम में व्यापक संशोधन पारित किए।",mr:"ब्रिटिश संसदेने 5 फेब्रुवारी 2026 रोजी ऑनलाइन सुरक्षा कायद्यात व्यापक दुरुस्त्या मंजूर केल्या."}, location:"international", category:"Technology", image:"https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=1600&auto=format&fit=crop", published:true, views:1450, createdAt:d(46) },
  { baseLanguage:"en", title:{en:"NASA's Europa Clipper Confirms Under-Ice Ocean Habitability",hi:"नासा के यूरोपा क्लिपर ने उप-बर्फ महासागर की रहने योग्य स्थिति की पुष्टि की",mr:"नासाच्या युरोपा क्लिपरने बर्फाखालील महासागराच्या राहण्यायोग्य स्थितीची पुष्टी केली"}, subHeading:{en:"New data suggests Jupiter's moon could sustain life",hi:"नया डेटा बताता है कि बृहस्पति के चंद्रमा पर जीवन संभव हो सकता है",mr:"नवीन डेटा सुचवतो की गुरुच्या चंद्रावर जीवन असू शकते"}, content:{en:"NASA's Europa Clipper mission sent back breakthrough data on March 18, 2026, confirming the presence of chemical energy sources in the moon's subsurface ocean. Scientists say this significantly increases the odds of finding microbial life.",hi:"नासा के यूरोपा क्लिपर ने 18 मार्च 2026 को बृहस्पति के चंद्रमा यूरोपा पर जीवन के संकेतों की पुष्टि की।",mr:"नासाच्या युरोपा क्लिपरने 18 मार्च 2026 रोजी गुरुच्या युरोपा चंद्रावर जीवनाच्या संकेतांची पुष्टी केली."}, location:"international", category:"Science", image:"https://images.unsplash.com/photo-1454789548928-9efd52dc4031?q=80&w=1600&auto=format&fit=crop", published:true, views:3120, createdAt:d(5) },
  { baseLanguage:"en", title:{en:"Brazil Announces Amazon Rainforest Deforestation Dropped 60%",hi:"ब्राजील ने अमेज़न वर्षावन कटाई में 60% की गिरावट की घोषणा की",mr:"ब्राझिलने अमेझॉन वर्षावन तोडीत 60% घट झाल्याची घोषणा केली"}, subHeading:{en:"Strict enforcement under President Lula shows major environmental gains",hi:"राष्ट्रपति लूला के नेतृत्व में कड़े प्रवर्तन से बड़े पर्यावरणीय लाभ",mr:"अध्यक्ष लुला यांच्या नेतृत्वाखालील कडक अंमलबजावणीमुळे मोठे पर्यावरणीय फायदे"}, content:{en:"The Brazilian government reported on March 12, 2026, that Amazon deforestation fell by 60% in the last 12 months. This is the lowest level in a decade, following aggressive military-backed operations against illegal logging and mining.",hi:"ब्राजील सरकार ने 12 मार्च 2026 को अमेज़न जंगलों की कटाई में 60% कमी दर्ज की।",mr:"ब्राझील सरकारने 12 मार्च 2026 रोजी अमेझॉन जंगलांच्या तोडीत 60% घट झाल्याची नोंद केली."}, location:"international", category:"Environment", image:"https://images.unsplash.com/photo-1542332213-9b5a5a3fad35?q=80&w=1600&auto=format&fit=crop", published:true, views:2450, createdAt:d(11) },
  { baseLanguage:"en", title:{en:"Japan Launches World's First Commercial 6G Network",hi:"जापान ने दुनिया का पहला कमर्शियल 6G नेटवर्क लॉन्च किया",mr:"जपानने जगातील पहिले व्यावसायिक 6G नेटवर्क लॉन्च केले"}, subHeading:{en:"Speeds up to 100 times faster than 5G; Tokyo becomes first 6G city",hi:"5G से 100 गुना तेज गति; टोक्यो बना पहला 6G शहर",mr:"5G पेक्षा 100 पट जास्त वेग; टोकियो बनले पहिले 6G शहर"}, content:{en:"NTT Docomo and Sony officially launched the world's first commercial 6G network in Tokyo on February 15, 2026. The new standard promises ultra-low latency and data transfer speeds up to 1 Terabit per second, enabling real-time holographic communication.",hi:"जापान ने 15 फरवरी 2026 को टोक्यो में व्यावसायिक 6G नेटवर्क शुरू किया।",mr:"जपानने 15 फेब्रुवारी 2026 रोजी टोकियोमध्ये व्यावसायिक 6G नेटवर्क सुरू केले."}, location:"international", category:"Technology", image:"https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1600&auto=format&fit=crop", published:true, views:4890, createdAt:d(36) },
  { baseLanguage:"en", title:{en:"Golden State Warriors Win NBA In-Season Tournament 2026",hi:"गोल्डन स्टेट वारियर्स ने NBA इन-सीज़न टूर्नामेंट 2026 जीता",mr:"गोल्डन स्टेट वॉरियर्सने NBA इन-सीझन टूर्नामेंट 2026 जिंकले"}, subHeading:{en:"Stephen Curry's masterclass leads Warriors past Celtics in Vegas",hi:"स्टीफन करी के शानदार प्रदर्शन से वारियर्स ने सेल्टिक्स को हराया",mr:"स्टीफन करीच्या चमकदार कामगिरीने वॉरियर्सनी सेल्टिक्सवर मात केली"}, content:{en:"The Golden State Warriors captured the 2026 NBA In-Season Tournament trophy on March 2, 2026, in Las Vegas. Stephen Curry scored 42 points to defeat the Boston Celtics 118-114. Curry was named the tournament MVP.",hi:"गोल्डन स्टेट वारियर्स ने 2 मार्च 2026 को NBA इन-सीज़न कप जीता।",mr:"गोल्डन स्टेट वॉरियर्सनी 2 मार्च 2026 रोजी NBA इन-सीझन कप जिंकला."}, location:"international", category:"Sports", image:"https://images.unsplash.com/photo-1504450758481-7338eba7524a?q=80&w=1600&auto=format&fit=crop", published:true, views:3670, createdAt:d(21) },
];
