// National (India) News - Real trending news from Jan-Mar 2026
const now = Date.now();
const d = (days) => new Date(now - days * 86400000);

export const nationalNews = [
  { baseLanguage:"en", title:{en:"ISRO Successfully Tests Gaganyaan Crew Escape System",hi:"ISRO ने गगनयान क्रू एस्केप सिस्टम का सफल परीक्षण किया",mr:"ISRO ने गगनयान क्रू एस्केप सिस्टमची यशस्वी चाचणी केली"}, subHeading:{en:"Key safety milestone cleared ahead of India's first manned space mission",hi:"भारत के पहले मानव मिशन से पहले प्रमुख सुरक्षा मील का पत्थर",mr:"भारताच्या पहिल्या मानवी मोहिमेपूर्वी प्रमुख सुरक्षा टप्पा पार"}, content:{en:"ISRO conducted the Crew Escape System test for Gaganyaan at Sriharikota on March 2, 2026. The abort mission simulated an emergency during ascent and the crew module descended safely. ISRO Chairman said the manned mission is on track for late 2026.",hi:"ISRO ने 2 मार्च 2026 को गगनयान क्रू एस्केप सिस्टम की सफल परीक्षा की।",mr:"ISRO ने 2 मार्च 2026 रोजी गगनयान क्रू एस्केप सिस्टमची यशस्वी चाचणी केली."}, location:"national", category:"National", image:"https://images.unsplash.com/photo-1628126235206-5260b9ea6441?q=80&w=1600&auto=format&fit=crop", published:true, views:4230, createdAt:d(21) },

  { baseLanguage:"en", title:{en:"Union Budget 2026: Record ₹11.2 Lakh Crore for Infrastructure",hi:"केंद्रीय बजट 2026: बुनियादी ढांचे के लिए रिकॉर्ड ₹11.2 लाख करोड़",mr:"केंद्रीय अर्थसंकल्प 2026: पायाभूत सुविधांसाठी विक्रमी ₹11.2 लाख कोटी"}, subHeading:{en:"FM Sitharaman announces focus on railways, highways and semiconductors",hi:"वित्त मंत्री सीतारमण ने रेल, राजमार्ग और सेमीकंडक्टर पर ध्यान की घोषणा की",mr:"अर्थमंत्री सीतारामण यांनी रेल्वे, महामार्ग आणि सेमीकंडक्टरवर लक्ष केंद्रित करण्याची घोषणा केली"}, content:{en:"Finance Minister Sitharaman presented Union Budget 2026-27 on February 1, 2026, with record ₹11.2L Cr capex. Six Vande Bharat routes, 25,000 km highways, and ₹50,000 Cr semiconductor fund announced. Sensex rose 2.1% on budget day.",hi:"वित्त मंत्री ने 1 फरवरी 2026 को ₹11.2 लाख करोड़ पूंजीगत व्यय के साथ बजट प्रस्तुत किया।",mr:"अर्थमंत्र्यांनी 1 फेब्रुवारी 2026 रोजी ₹11.2 लाख कोटी भांडवली खर्चासह अर्थसंकल्प सादर केला."}, location:"national", category:"National", image:"https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1600&auto=format&fit=crop", published:true, views:4980, createdAt:d(50) },

  { baseLanguage:"en", title:{en:"India Beat England 4-1 in Home Test Series",hi:"भारत ने इंग्लैंड को घरेलू टेस्ट सीरीज में 4-1 से हराया",mr:"भारताने घरच्या मैदानावर इंग्लंडला कसोटी मालिकेत 4-1 ने हरवले"}, subHeading:{en:"Bumrah takes 32 wickets; Ashwin announces retirement",hi:"बुमराह ने 32 विकेट लिए; अश्विन ने संन्यास की घोषणा की",mr:"बुमराहने 32 बळी घेतले; अश्विनने निवृत्तीची घोषणा केली"}, content:{en:"India completed a 4-1 Test series win against England on February 28, 2026. Bumrah took 32 wickets. R Ashwin announced retirement after the final Test in Dharamsala, finishing with 537 Test wickets.",hi:"भारत ने 28 फरवरी 2026 को इंग्लैंड पर 4-1 से टेस्ट सीरीज जीत हासिल की।",mr:"भारताने 28 फेब्रुवारी 2026 रोजी इंग्लंडवर 4-1 ने कसोटी मालिका विजय मिळवला."}, location:"national", category:"Sports", image:"https://images.unsplash.com/photo-1540747913346-19e32fc3e64b?q=80&w=1600&auto=format&fit=crop", published:true, views:4750, createdAt:d(23) },

  { baseLanguage:"en", title:{en:"India's GDP Grows 7.0% in Q3 FY26",hi:"भारत की GDP Q3 FY26 में 7.0% बढ़ी",mr:"भारताची GDP Q3 FY26 मध्ये 7.0% वाढली"}, subHeading:{en:"Manufacturing at 8.4%; RBI maintains growth outlook",hi:"विनिर्माण 8.4% पर; RBI ने विकास दृष्टिकोण बनाए रखा",mr:"उत्पादन 8.4% वर; RBI ने विकास दृष्टिकोन कायम ठेवला"}, content:{en:"India's GDP grew 7.0% in Q3 FY26 (Oct-Dec 2025). Manufacturing surged 8.4%, services at 6.8%. RBI maintained 6.8% full-year forecast noting improving private investment and strong consumption.",hi:"भारत की GDP Q3 FY26 में 7.0% बढ़ी। विनिर्माण 8.4% पर रहा।",mr:"भारताची GDP Q3 FY26 मध्ये 7.0% वाढली. उत्पादन 8.4% वर."}, location:"national", category:"Business", image:"https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=1600&auto=format&fit=crop", published:true, views:3150, createdAt:d(23) },

  { baseLanguage:"en", title:{en:"Delhi Assembly Elections 2026: AAP Wins Third Term",hi:"दिल्ली चुनाव 2026: AAP की लगातार तीसरी जीत",mr:"दिल्ली निवडणूक 2026: AAP चा सलग तिसरा विजय"}, subHeading:{en:"AAP 48 seats, BJP 18, Congress 4 in 70-seat Assembly",hi:"AAP 48, BJP 18, कांग्रेस 4 सीटें 70 सदस्यीय विधानसभा में",mr:"70 जागांच्या विधानसभेत AAP 48, BJP 18, काँग्रेस 4"}, content:{en:"AAP won 48 of 70 seats in Delhi Assembly Elections on February 15, 2026. BJP improved to 18 seats. Congress won 4. Voter turnout was 62.3%.",hi:"AAP ने 15 फरवरी 2026 को दिल्ली चुनाव में 70 में से 48 सीटें जीतीं।",mr:"AAP ने 15 फेब्रुवारी 2026 रोजी 70 पैकी 48 जागा जिंकल्या."}, location:"national", category:"National", image:"https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?q=80&w=1600&auto=format&fit=crop", published:true, views:4650, createdAt:d(36) },

  { baseLanguage:"en", title:{en:"Sensex Crosses 82,000 for First Time",hi:"सेंसेक्स पहली बार 82,000 के पार",mr:"सेन्सेक्स पहिल्यांदा 82,000 पार"}, subHeading:{en:"FII inflows and strong Q3 earnings drive rally",hi:"FII प्रवाह और मजबूत Q3 आय ने तेजी का नेतृत्व किया",mr:"FII प्रवाह आणि मजबूत Q3 कमाईने तेजी आणली"}, content:{en:"BSE Sensex breached 82,000 for the first time on March 10, 2026, driven by FII inflows of ₹15,000 Cr in March and strong Q3 earnings. TCS, Infosys, HDFC Bank led gains.",hi:"BSE सेंसेक्स ने 10 मार्च 2026 को पहली बार 82,000 का आंकड़ा पार किया।",mr:"BSE सेन्सेक्सने 10 मार्च 2026 रोजी पहिल्यांदा 82,000 चा टप्पा पार केला."}, location:"national", category:"Business", image:"https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=1600&auto=format&fit=crop", published:true, views:2980, createdAt:d(13) },

  { baseLanguage:"en", title:{en:"RBI Cuts Repo Rate by 25 Basis Points to 6.25%",hi:"RBI ने रेपो दर 25 आधार अंक घटाकर 6.25% किया",mr:"RBI ने रेपो दर 25 बेसिस पॉइंट्सने 6.25% पर्यंत कमी केला"}, subHeading:{en:"First rate cut in two years signals easing inflation outlook",hi:"दो वर्षों में पहली दर कटौती मुद्रास्फीति कम होने का संकेत",mr:"दोन वर्षांतील पहिली दर कपात चलनवाढ कमी होण्याचे संकेत"}, content:{en:"The Reserve Bank of India cut the repo rate by 25bp to 6.25% on February 7, 2026 — the first cut since April 2024. RBI Governor Das cited easing inflationary pressures and strong growth momentum. Home and auto loan EMIs are expected to reduce.",hi:"RBI ने 7 फरवरी 2026 को रेपो दर 25bp घटाकर 6.25% किया।",mr:"RBI ने 7 फेब्रुवारी 2026 रोजी रेपो दर 25bp ने 6.25% पर्यंत कमी केला."}, location:"national", category:"Business", image:"https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=1600&auto=format&fit=crop", published:true, views:3800, createdAt:d(44) },

  { baseLanguage:"en", title:{en:"India Launches Digital Health ID for All Citizens",hi:"भारत ने सभी नागरिकों के लिए डिजिटल हेल्थ ID लॉन्च की",mr:"भारताने सर्व नागरिकांसाठी डिजिटल हेल्थ ID लॉन्च केली"}, subHeading:{en:"Ayushman Bharat Digital Mission reaches 50 Cr registrations",hi:"आयुष्मान भारत डिजिटल मिशन 50 करोड़ पंजीकरण तक पहुंचा",mr:"आयुष्मान भारत डिजिटल मिशन 50 कोटी नोंदणीवर पोहोचले"}, content:{en:"PM Modi announced on January 26, 2026, that Ayushman Bharat Digital Health Mission crossed 50 Cr registrations. The universal health ID integrates medical records across hospitals nationally, enabling seamless portability.",hi:"PM मोदी ने 26 जनवरी 2026 को 50 करोड़ पंजीकरण की घोषणा की।",mr:"PM मोदींनी 26 जानेवारी 2026 रोजी 50 कोटी नोंदणीची घोषणा केली."}, location:"national", category:"Health", image:"https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=1600&auto=format&fit=crop", published:true, views:2100, createdAt:d(56) },

  { baseLanguage:"en", title:{en:"Indian Women's Cricket Team Reaches T20 World Cup Final",hi:"भारतीय महिला क्रिकेट टीम T20 विश्व कप फाइनल में",mr:"भारतीय महिला क्रिकेट संघ T20 विश्वचषक फायनलमध्ये"}, subHeading:{en:"Smriti Mandhana's century guides India past Australia in semi-final",hi:"स्मृति मंधाना की शतक से भारत ने सेमीफाइनल में ऑस्ट्रेलिया को हराया",mr:"स्मृति मंधानाच्या शतकाने भारताने सेमीफायनलमध्ये ऑस्ट्रेलियाला हरवले"}, content:{en:"India's women's cricket team reached the T20 World Cup final on March 14, 2026, beating Australia by 28 runs. Smriti Mandhana scored an unbeaten 102. The final against England is scheduled for March 17 in Colombo.",hi:"भारतीय महिला टीम ने 14 मार्च 2026 को ऑस्ट्रेलिया को 28 रनों से हराकर फाइनल में प्रवेश किया।",mr:"भारतीय महिला संघाने 14 मार्च 2026 रोजी ऑस्ट्रेलियाला 28 धावांनी हरवून फायनलमध्ये प्रवेश केला."}, location:"national", category:"Sports", image:"https://images.unsplash.com/photo-1540747913346-19e32fc3e64b?q=80&w=1600&auto=format&fit=crop", published:true, views:4400, createdAt:d(9) },

  { baseLanguage:"en", title:{en:"UPI Crosses 20 Billion Monthly Transactions in February",hi:"UPI ने फरवरी में मासिक 20 अरब लेनदेन पार किए",mr:"UPI ने फेब्रुवारीमध्ये मासिक 20 अब्ज व्यवहार पार केले"}, subHeading:{en:"India's digital payments infrastructure hits new global record",hi:"भारत का डिजिटल भुगतान बुनियादी ढांचा नए वैश्विक रिकॉर्ड पर",mr:"भारताच्या डिजिटल पेमेंट इन्फ्रास्ट्रक्चरने नवा जागतिक विक्रम केला"}, content:{en:"UPI processed 20.3 billion transactions worth ₹23.4 lakh crore in February 2026, crossing the 20 billion monthly milestone for the first time. NPCI CEO said UPI is now the world's largest real-time payment system by transaction volume.",hi:"UPI ने फरवरी 2026 में 20.3 अरब लेनदेन किए।",mr:"UPI ने फेब्रुवारी 2026 मध्ये 20.3 अब्ज व्यवहार केले."}, location:"national", category:"Technology", image:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600&auto=format&fit=crop", published:true, views:2650, createdAt:d(27) },

  { baseLanguage:"en", title:{en:"Supreme Court Upholds Right to Privacy in Digital Surveillance Case",hi:"सुप्रीम कोर्ट ने डिजिटल निगरानी मामले में गोपनीयता के अधिकार को बरकरार रखा",mr:"सुप्रीम कोर्टने डिजिटल पाळत ठेवणे प्रकरणात गोपनीयतेचा अधिकार कायम ठेवला"}, subHeading:{en:"Landmark ruling requires judicial oversight for all government surveillance",hi:"ऐतिहासिक निर्णय में सभी सरकारी निगरानी के लिए न्यायिक निरीक्षण अनिवार्य",mr:"ऐतिहासिक निर्णयात सर्व सरकारी पाळत ठेवण्यासाठी न्यायिक देखरेख अनिवार्य"}, content:{en:"The Supreme Court ruled on March 5, 2026, that all government digital surveillance must have prior judicial approval. The 5-judge bench unanimously upheld privacy as a fundamental right, striking down provisions of the IT Act that allowed warrantless surveillance.",hi:"सुप्रीम कोर्ट ने 5 मार्च 2026 को निर्णय दिया कि सभी सरकारी डिजिटल निगरानी में न्यायिक मंजूरी अनिवार्य है।",mr:"सुप्रीम कोर्टने 5 मार्च 2026 रोजी निर्णय दिला की सर्व सरकारी डिजिटल पाळत ठेवण्यात न्यायिक मंजुरी अनिवार्य आहे."}, location:"national", category:"National", image:"https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=1600&auto=format&fit=crop", published:true, views:3400, createdAt:d(18) },

  { baseLanguage:"en", title:{en:"India Signs Free Trade Agreement with European Union",hi:"भारत ने यूरोपीय संघ के साथ मुक्त व्यापार समझौते पर हस्ताक्षर किए",mr:"भारताने युरोपियन युनियनसोबत मुक्त व्यापार कराराची स्वाक्षरी केली"}, subHeading:{en:"Historic deal reduces tariffs on 90% of goods traded",hi:"ऐतिहासिक समझौते में 90% व्यापारित वस्तुओं पर शुल्क में कमी",mr:"ऐतिहासिक करारात 90% व्यापारी वस्तूंवरील शुल्क कमी"}, content:{en:"India and the EU signed a comprehensive Free Trade Agreement on March 18, 2026, after 16 years of negotiations. The deal eliminates tariffs on 90% of goods, opens services trade, and includes provisions on digital commerce and sustainability.",hi:"भारत और EU ने 18 मार्च 2026 को 16 वर्षों की बातचीत के बाद FTA पर हस्ताक्षर किए।",mr:"भारत आणि EU ने 18 मार्च 2026 रोजी 16 वर्षांच्या वाटाघाटीनंतर FTA वर स्वाक्षरी केली."}, location:"national", category:"Business", image:"https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=1600&auto=format&fit=crop", published:true, views:2890, createdAt:d(5) },

  { baseLanguage:"en", title:{en:"Vande Bharat Sleeper Train: India's First High-Speed Sleeper Unveiled",hi:"वंदे भारत स्लीपर ट्रेन: भारत की पहली हाई-स्पीड स्लीपर अनावरण",mr:"वंदे भारत स्लीपर ट्रेन: भारतातील पहिली हाय-स्पीड स्लीपर अनावरण"}, subHeading:{en:"Chennai-Bangalore-Mysore route to be the first; top speed 200 kmph",hi:"चेन्नई-बैंगलोर-मैसूर मार्ग पहला होगा; अधिकतम गति 200 किमी/घंटा",mr:"चेन्नई-बंगळुरू-म्हैसूर मार्ग पहिला; कमाल वेग 200 किमी/तास"}, content:{en:"Indian Railways unveiled the Vande Bharat Sleeper prototype on January 15, 2026. The train features AC 2-tier and 3-tier configurations with 200 kmph top speed. The Chennai-Bangalore-Mysore corridor will be the first route, expected to begin service by October 2026.",hi:"भारतीय रेलवे ने 15 जनवरी 2026 को वंदे भारत स्लीपर का प्रोटोटाइप पेश किया।",mr:"भारतीय रेल्वेने 15 जानेवारी 2026 रोजी वंदे भारत स्लीपरचा प्रोटोटाइप सादर केला."}, location:"national", category:"Infrastructure", image:"https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=1600&auto=format&fit=crop", published:true, views:3900, createdAt:d(67) },

  { baseLanguage:"en", title:{en:"PM Modi Inaugurates India's First Semiconductor Fab in Gujarat",hi:"PM मोदी ने गुजरात में भारत की पहली सेमीकंडक्टर फैब का उद्घाटन किया",mr:"PM मोदींनी गुजरातमध्ये भारतातील पहिल्या सेमीकंडक्टर फॅबचे उद्घाटन केले"}, subHeading:{en:"Tata-TSMC joint venture begins 28nm chip production",hi:"टाटा-TSMC संयुक्त उद्यम ने 28nm चिप उत्पादन शुरू किया",mr:"टाटा-TSMC संयुक्त उपक्रमाने 28nm चिप उत्पादन सुरू केले"}, content:{en:"PM Modi inaugurated India's first operational semiconductor fabrication plant in Dholera, Gujarat, on March 20, 2026. The Tata-TSMC joint venture will produce 28nm chips for automotive and telecom sectors, reducing India's chip import dependency.",hi:"PM मोदी ने 20 मार्च 2026 को धोलेरा, गुजरात में भारत की पहली सेमीकंडक्टर फैब का उद्घाटन किया।",mr:"PM मोदींनी 20 मार्च 2026 रोजी धोलेरा, गुजरातमध्ये भारतातील पहिल्या सेमीकंडक्टर फॅबचे उद्घाटन केले."}, location:"national", category:"Technology", image:"https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1600&auto=format&fit=crop", published:true, views:4100, createdAt:d(3) },

  { baseLanguage:"en", title:{en:"Indian Government Announces Expansion of PLI Scheme for IT Hardware",hi:"भारत सरकार ने IT हार्डवेयर के लिए PLI योजना विस्तार की घोषणा की",mr:"भारत सरकारने IT हार्डवेअरसाठी PLI योजना विस्ताराची घोषणा केली"}, subHeading:{en:"New incentives to boost local manufacturing of laptops and servers",hi:"लैपटॉप और सर्वर के स्थानीय निर्माण को बढ़ावा देने के लिए नए प्रोत्साहन",mr:"लॅपटॉप आणि सर्व्हरच्या स्थानिक उत्पादनाला चालना देण्यासाठी नवीन प्रोत्साहन"}, content:{en:"The Ministry of Electronics and IT announced an expanded PLI 2.0 scheme for IT hardware on February 20, 2026. The ₹17,000 Cr scheme aims to achieve $300B in electronics production by 2027, with special focus on high-end servers and AI hardware.",hi:"भारत सरकार ने 20 फरवरी 2026 को IT हार्डवेयर के लिए ₹17,000 करोड़ की PLI योजना की घोषणा की।",mr:"भारत सरकारने 20 फेब्रुवारी 2026 रोजी IT हार्डवेअरसाठी ₹17,000 कोटींच्या PLI योजनेची घोषणा केली."}, location:"national", category:"Business", image:"https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1600&auto=format&fit=crop", published:true, views:2450, createdAt:d(31) },
  { baseLanguage:"en", title:{en:"Rajasthan Unveils India's Largest Floating Solar Plant in Jaipur",hi:"राजस्थान ने जयपुर में भारत के सबसे बड़े फ्लोटिंग सोलर प्लांट का अनावरण किया",mr:"राजस्थानने जयपूरमध्ये भारतातील सर्वात मोठ्या फ्लोटिंग सोलर प्लांटचे अनावरण केले"}, subHeading:{en:"200 MW facility on Ramgarh Lake to power 1.5 lakh rural households",hi:"रामगढ़ झील पर 200 MW सुविधा से 1.5 लाख ग्रामीण घरों को बिजली",mr:"रामगड तलावावरील 200 MW सुविधेने 1.5 लाख ग्रामीण घरांना वीज"}, content:{en:"The Rajasthan government inaugurated a 200 MW floating solar power plant on Ramgarh Lake near Jaipur on March 5, 2026. This is now India's largest floating solar facility, expected to reduce water evaporation by 30% while generating clean energy.",hi:"राजस्थान ने 5 मार्च 2026 को जयपुर के पास 200 MW का फ्लोटिंग सोलर प्लांट शुरू किया।",mr:"राजस्थानने 5 मार्च 2026 रोजी जयपूरजवळ 200 MW चा फ्लोटिंग सोलर प्लांट सुरू केला."}, location:"national", category:"Infrastructure", image:"https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=1600&auto=format&fit=crop", published:true, views:1890, createdAt:d(18) },
  { baseLanguage:"en", title:{en:"India's First Undersea Rail Tunnel Nears Completion in Mumbai",hi:"मुंबई में भारत की पहली समुद्री रेल सुरंग पूर्णता के करीब",mr:"मुंबईतील भारतातील पहिली समुद्राखालची रेल्वे बोगदा पूर्ण होण्याच्या मार्गावर"}, subHeading:{en:"7 km stretch under Thane Creek part of Mumbai-Ahmedabad Bullet Train",hi:"ठाणे क्रीक के नीचे 7 किमी का हिस्सा मुंबई-अहमदाबाद बुलेट ट्रेन का हिस्सा",mr:"ठाणे खाडीखालील 7 किमीचा भाग मुंबई-अहमदाबाद बुलेट ट्रेनचा भाग"}, content:{en:"Construction of India's first undersea rail tunnel, a 7 km stretch under the sea at Thane Creek, reached 90% completion on March 15, 2026. Part of the Mumbai-Ahmedabad High-Speed Rail corridor, it will be the first of its kind in India.",hi:"भारत की पहली समुद्री रेल सुरंग का निर्माण 15 मार्च 2026 तक 90% पूरा हो गया।",mr:"भारतातील पहिल्या समुद्राखालच्या रेल्वे बोगद्याचे बांधकाम 15 मार्च 2026 पर्यंत 90% पूर्ण झाले."}, location:"national", category:"Infrastructure", image:"https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=1600&auto=format&fit=crop", published:true, views:3120, createdAt:d(8) },
  { baseLanguage:"en", title:{en:"Bengaluru Airport Terminal 3 Inaugurated; Handles 100M Passengers",hi:"बेंगलुरु एयरपोर्ट टर्मिनल 3 का उद्घाटन; 10 करोड़ यात्रियों की क्षमता",mr:"बेंगळुरू विमानतळ टर्मिनल 3 चे उद्घाटन; 10 कोटी प्रवाशांची क्षमता"}, subHeading:{en:"New 'Terminal in a Forest' design wins global architecture award",hi:"नए 'टर्मिनल इन ए फॉरेस्ट' डिजाइन ने वैश्विक वास्तुकला पुरस्कार जीता",mr:"नवीन 'टर्मिनल इन अ फॉरेस्ट' डिझाइनने जागतिक वास्तुकला पुरस्कार जिंकला"}, content:{en:"PM Modi inaugurated the third terminal at Bengaluru's Kempegowda International Airport on February 15, 2026. The ₹13,000 Cr terminal increases the airport's capacity to 100 million passengers annually and features advanced biometric entry systems.",hi:"PM मोदी ने 15 फरवरी 2026 को बेंगलुरु एयरपोर्ट के तीसरे टर्मिनल का उद्घाटन किया।",mr:"PM मोदींनी 15 फेब्रुवारी 2026 रोजी बेंगळुरू विमानतळाच्या तिसऱ्या टर्मिनलचे उद्घाटन केले."}, location:"national", category:"Infrastructure", image:"https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?q=80&w=1600&auto=format&fit=crop", published:true, views:4560, createdAt:d(36) },
  { baseLanguage:"en", title:{en:"Indian Pharma Giant Receives USFDA Approval for Generic Cancer Drug",hi:"भारतीय फार्मा दिग्गज को जेनेरिक कैंसर दवा के लिए USFDA की मंजूरी मिली",mr:"भारतीय फार्मा दिग्गज कंपनीला जेनेरिक कॅन्सर औषधासाठी USFDA ची मंजुरी"}, subHeading:{en:"Breakthrough expected to lower chemotherapy costs globally",hi:"कीमोथेरेपी की लागत वैश्विक स्तर पर कम होने की उम्मीद",mr:"किमोथेरपीचा खर्च जागतिक स्तरावर कमी होण्याची अपेक्षा"}, content:{en:"A leading Indian pharmaceutical company received USFDA approval for its generic version of a major chemotherapy drug on January 28, 2026. This approval is expected to reduce the cost of treatment by up to 70% in international markets.",hi:"भारतीय फार्मा कंपनी को 28 जनवरी 2026 को कैंसर की दवा के लिए USFDA मंजूरी मिली।",mr:"भारतीय फार्मा कंपनीला 28 जानेवारी 2026 रोजी कॅन्सरच्या औषधासाठी USFDA मंजुरी मिळाली."}, location:"national", category:"Health", image:"https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=1600&auto=format&fit=crop", published:true, views:2780, createdAt:d(54) },
];
